namespace: djinn
driver:
  type: qemu
  image: djinn-dev
sources:
- https://github.com/andrewpillar/djinn.git => djinn
env:
- LDFLAGS=-s -w
stages:
- test
- make
jobs:
- stage: test
  commands:
  - cd djinn
  - go test -cover ./...
  - go test -v -tags "integration" ./integration
- stage: make
  commands:
  - cd djinn
  - ./make.sh runner
  - ./make.sh scheduler
  - ./make.sh server
  - ./make.sh worker
  - ./make.sh manif
  artifacts:
  - bin/djinn
  - bin/djinn-scheduler
  - bin/djinn-server
  - bin/djinn-worker
  - sum.manif
