namespace: djinn
driver:
  type: qemu
  image: djinn-dev
sources:
- https://github.com/andrewpillar/djinn.git => djinn
env:
- LDFLAGS=-s -w
stages:
- integration
- make
jobs:
- stage: integration
  commands:
  - cd djinn
  - go test -v -tags "integration" ./integration
- stage: make
  commands:
  - cd djinn
  - ./make.sh
  artifacts:
  - bin/djinn
  - bin/djinn-curator
  - bin/djinn-scheduler
  - bin/djinn-server
  - bin/djinn-worker
  - sum.manif
