namespace: djinn
driver:
  type: qemu
  image: djinn-dev
sources:
- https://github.com/andrewpillar/djinn.git => thrall
env:
- PGADDR=host=localhost port=5432 dbname=thrall user=thrall password=secret sslmode=disable
- RDADDR=localhost:6379
- LDFLAGS=-s -w
stages:
- test
- make
jobs:
- stage: test
  commands:
  - cd thrall
  - go test -cover ./...
  - go test -tags "integration" ./integration
- stage: make
  commands:
  - cd thrall
  - ./make.sh runner
  - ./make.sh server
  - ./make.sh worker
  artifacts:
  - integration/server.log
  - djinn.out
  - djinn-server.out
  - djinn-worker.out
