namespace: djinn
driver:
  type: qemu
  image: djinn-dev
sources:
- https://github.com/djinn-ci/djinn
env:
- LDFLAGS=-s -w
- INTEGRATION_CONFIG=testdata/server.cfg
stages:
- setup
- make
jobs:
- stage: setup
  commands:
  - cd djinn
  - mgrt run -type postgresql -dsn "host=localhost port=5432 dbname=djinn user=mgrt password=secret"
  - sudo -u postgres psql -c "ALTER USER djinn_curator WITH PASSWORD 'secret'"
  - sudo -u postgres psql -c "ALTER USER djinn_scheduler WITH PASSWORD 'secret'"
  - sudo -u postgres psql -c "ALTER USER djinn_server WITH PASSWORD 'secret'"
  - sudo -u postgres psql -c "ALTER USER djinn_worker WITH PASSWORD 'secret'"
- stage: make
  commands:
  - cd djinn
  - ./make.sh
  artifacts:
  - djinn/bin/djinn
  - djinn/bin/djinn-curator
  - djinn/bin/djinn-scheduler
  - djinn/bin/djinn-server
  - djinn/bin/djinn-worker
  - djinn/bin/sum.manif
