namespace: djinn
driver:
  type: qemu
  image: djinn-dev
sources:
- https://github.com/djinn-ci/djinn
env:
- PGPASSWORD=secret
- LDFLAGS=-s -w
- INTEGRATION_CONFIG=testdata/server.cfg
stages:
- setup
- make
jobs:
- stage: setup
  commands:
  - psql -U djinn -h localhost -d djinn -f djinn/schema.sql
- stage: make
  commands:
  - cd djinn
  - ./make.sh
  artifacts:
  - djinn/bin/djinn
  - djinn/bin/djinn-curator
  - djinn/bin/djinn-scheduler
  - djinn/bin/djinn-server
  - djinn/bin/djinn-worker
  - djinn/bin/sum.manif
