namespace: djinn
driver:
  type: qemu
  image: djinn-dev
sources:
- https://github.com/djinn-ci/djinn
- https://github.com/andrewpillar/mgrt v3
env:
- LDFLAGS=-s -w
- INTEGRATION_CONFIG_DIR=testdata
- PGDSN=host=localhost port=5432 dbname=djinn user=mgrt password=secret
stages:
- deps
- setup
- make
jobs:
- stage: deps
  commands:
  - cd mgrt
  - ./make.sh
  - cp bin/mgrt /usr/local/bin/mgrt
- stage: setup
  commands:
  - printf "127.0.0.1\tlocal.dev\n" | tee -a /etc/hosts
  - cd djinn
  - mgrt run -c schema -type postgresql -dsn $PGDSN
  - mgrt run -c perms -type postgresql -dsn $PGDSN
  - mgrt run -c dev -type postgresql -dsn $PGDSN
- stage: make
  commands:
  - cd djinn
  - ./make.sh
  artifacts:
  - djinn/integration/testdata/log/server.log
  - djinn/integration/testdata/log/webhook.log
  - djinn/integration/testdata/log/worker.log
  - djinn/bin/djinn
  - djinn/bin/djinn-consumer
  - djinn/bin/djinn-curator
  - djinn/bin/djinn-scheduler
  - djinn/bin/djinn-server
  - djinn/bin/djinn-worker
  - djinn/bin/sum.manif
