namespace: djinn
driver:
  type: qemu
  image: djinn-dev
sources:
- https://github.com/andrewpillar/djinn.git => djinn
env:
- PGADDR=host=localhost port=5432 dbname=djinn user=djinn password=secret sslmode=disable
- RDADDR=localhost:6379
- LDFLAGS=-s -w
stages:
- test
- make
jobs:
- stage: test
  commands:
  - cd djinn
  - go test -cover ./...
  - go test -tags "integration" ./integration
- stage: make
  commands:
  - cd djinn
  - ./make.sh runner
  - ./make.sh server
  - ./make.sh worker
  artifacts:
  - bin/djinn
  - bin/djinn-server
  - bin/djinn-worker
  - sum.manif
