driver:
  type: docker
  image: golang
  workspace: /go
sources:
  - https://github.com/andrewpillar/mgrt
objects:
  - .thrall.yml => /go/src/some-file
stages:
  - test
  - build
allow_failures:
  - test
jobs:
  - stage: test
    commands:
      - ls
      - echo foo
  - stage: test
    commands:
      - echo bar
  - stage: test
    commands:
      - pwd
      - echo zap
    depends:
      - test.1
