driver:
  type: docker
  image: golang
  workspace: /go
sources:
  - url: https://github.com/andrewpillar/jrnl
stages:
  - test
  - build
jobs:
  - stage: test
    commands:
      - cd /go/jrnl
      - GO111MODULE=on go test ./... -cover
  - stage: build
    commands:
      - cd /go/jrnl
      - GO111MODULE=on go build
    artifacts:
      - /go/jrnl/jrnl
