driver:
  type: docker
  image: golang
  workspace: /go
sources:
  - https://github.com/andrewpillar/mgrt
objects:
  - some-file => /go/src/some-file
stages:
  - test
  - build
jobs:
  - stage: test
    commands:
      - cat src/some-file
      - cd mgrt
      - go test ./... -v -cover
  - stage: build
    commands:
      - cd mgrt
      - go build -o mgrt.out
    artifacts:
      - /go/mgrt/mgrt.out
