driver:
  type: docker
  image: golang
  workspace: /go
sources:
  - https://github.com/andrewpillar/jrnl
stages:
  - test
  - build
jobs:
  - stage: test
    commands:
      - cd /go/jrnl
      - go test ./... -v -cover
  - stage: build
    commands:
      - cd /go/jrnl
      - go build -tags 'netgo osusergo' -o jrnl.out
    artifacts:
      - /go/jrnl/jrnl.out
