driver:
  type: docker
  image: golang
  workspace: /go
sources:
  - https://github.com/andrewpillar/mgrt
objects:
  - .thrall.yml => /go/src/some-file
stages:
  - test
  - build
allow_failures:
  - test
jobs:
  - stage: test
    commands:
      - cat src/some-file
  - stage: build
    commands:
      - pwd
      - ls -la
