driver:
  type: qemu
  image: alpine/latest-stable
sources:
  - https://github.com/andrewpillar/jrnl v1.1.1
env:
  - MIRROR=http://alpine.mirror.wearetriple.com
stages:
  - packages
  - build
  - test
jobs:
  - stage: packages
    commands:
      - echo "$MIRROR/edge/community" >> /etc/apk/repositories
      - apk update
      - apk add musl-dev go
  - stage: build
    commands:
      - cd jrnl
      - go install
  - stage: test
    commands:
      - PATH="$PATH:$HOME/go/bin"
      - cd jrnl
      - ./test.sh
    artifacts:
      - /root/go/bin/jrnl => jrnl.out
